#!/bin/bash
#This is a general template for a shell script to run various stages and scripts of SORTER2, make sure to remove PBS/SBATCH settings if needed
#or uncomment lines that you wish to run

#Below is a template for submitting a shell batch job on a SLURM system, submitting it using the sbatch command
#-N : number of threads , -t : wall time used for run, -p : Name of compute partition/queue being used on HPC, 
#-A : name of allocation on HPC, -o : output log file, -e : output error log file
#SBATCH -N 1
#SBATCH -t 72:00:00
#SBATCH -p QueueName
#SBATCH -A Allocation_Name
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.err

#Below is a template for submitting a shell batch job on a PBS system, submitting it using the qsub command
# -q : Name of compute partition/queue being used on HPC, -l nodes=:ppn=: number of nodes and partitions per node being used, 
#-l walltime=: walltime used for run, -o : output logfile name, -j : output error logfile name, -N name for job, -A : name of allocation on HPC
#PBS -q QueueName
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -o out
#PBS -j oe
#PBS -N JobName
#PBS -A Allocation_Name


#If running job on SLURM or PBS, initialize bash and activate conda envrionment for SORTER2
#conda init bash
#conda activate SORTER2

#Set working path, if running stage1A should be the directory path containing formatted raw reads,
#if running other stages should be the directory path to the SORTER2 project folder generated by Stage1A

working_path=/your/working/path/

cd ${working_path}

#Stage1A
#Runs TrimGalore and SPAdes assembly with a project name of 'ProjectName'
#python SORTER2_Stage1A_TrimSPAdes2.py -n ProjectName -trim T -spades T

#Stage1B
#python SORTER2_Stage1B_AssembleOrthologs.py -wd /path/to/SORTER2_ProjectName/ -ref /path/to/bait_references.fasta -loci 455 -cl 0.70 -reclust F -csn 20 -csl 300 -al 1000 -indel 0.1 -idformat onlysample

#Stage 2
#python SORTER2_Stage2_PhaseOrthologs.py -wd /path/to/SORTER2_ProjectName/ -pq 20 -al 1000 -indel 0.1 -idformat phase

#Using SORTER2 Processor for alignment filtering and making vcf file for admixture
#python SORTER2_Processor.py -wd /path/to/SORTER2_ProjectName/ -rep 0.50 -mc 2 -al T -st2 F -st3 F -dovcf T

#Stage3
#python SORTER2_Stage3_PhaseHybrids.py -wd /path/to/SORTER2_ProjectName/ -ref /path/to/bait_references.fasta -loci 455 -csn 20 -csl 300 -pq 20 -al 1000 -indel 0.1 -fp F


